/**
 * BAILII (British and Irish Legal Information Institute) integration
 *
 * ── What is BAILII? ──────────────────────────────────────────────────────────
 *
 * BAILII (https://www.bailii.org) is the authoritative free online source for
 * British and Irish primary legal materials. It is maintained by the British
 * and Irish Legal Information Institute, a registered charity, and has operated
 * since 2000. Courts and tribunals in England & Wales, Scotland, Northern
 * Ireland, and Ireland submit judgments directly to BAILII, making it the
 * closest equivalent to an official government repository of case law.
 *
 * ── What BAILII covers ───────────────────────────────────────────────────────
 *
 * - UK Supreme Court (UKSC) — from 2009 onwards
 * - House of Lords (UKHL) — from approx. 1946 onwards
 * - Privy Council (UKPC) — selected cases from 1999 onwards
 * - Court of Appeal Civil (EWCA Civ) — from 1996 onwards
 * - Court of Appeal Criminal (EWCA Crim) — from 1996 onwards
 * - High Court divisions (EWHC) — from 1996 onwards for most divisions
 * - Upper Tribunal, Employment Appeal Tribunal, First-tier Tribunal (Tax)
 * - Older cases: selected coverage back to the 19th century, but incomplete
 *
 * ── BAILII's authority and limitations ───────────────────────────────────────
 *
 * BAILII publishes the official judgment text as handed down by the court.
 * For cases with neutral citations (introduced from 2001 onwards), BAILII is
 * the definitive source — the neutral citation IS the official reference.
 *
 * However BAILII has important limitations:
 *
 * 1. OLDER CASES: Cases before ~1996 have incomplete BAILII coverage. The
 *    authoritative sources for older cases are the commercial law reports
 *    (Weekly Law Reports, All England Law Reports, AC, QB, Ch etc.) published
 *    by Incorporated Council of Law Reporting and LexisNexis. Access to these
 *    requires a subscription (Westlaw, LexisNexis, vLex).
 *
 * 2. HOLDING SUMMARIES: BAILII publishes the full judgment only — it does not
 *    provide editorial summaries or headnotes. The holding summaries in this
 *    report are AI-generated interpretations of the judgment, not official
 *    headnotes. They must be verified against the full text of the judgment.
 *
 * 3. SUBSEQUENT TREATMENT: BAILII does not indicate whether a case has been
 *    overruled, disapproved, distinguished, or departed from by later courts.
 *    Citator services (Westlaw "Cases+" or LexisNexis "Case Analysis") must
 *    be used to check whether a cited case remains good law.
 *
 * 4. UNREPORTED CASES: Some cases are not published on BAILII. A 404 response
 *    does not definitively prove a case does not exist — it may simply not be
 *    in BAILII's database, especially for older or specialist tribunal cases.
 *
 * 5. AI HALLUCINATION RISK: The citations in this report were generated by an
 *    AI language model. Even where a direct BAILII URL is constructed and
 *    resolves successfully, the case name and holding summary must be verified
 *    against the actual judgment. AI models can generate plausible-looking but
 *    incorrect citations, transpose parties, misstate years, or fabricate cases.
 *
 * ── Verification workflow for legal professionals ─────────────────────────────
 *
 * Recommended steps before relying on any citation in this report:
 *
 *  1. Click the BAILII link — confirm the page loads and the parties match
 *  2. Read the judgment — confirm the holding stated here is accurate
 *  3. Run a citator check on Westlaw or LexisNexis — confirm the case is
 *     still good law and has not been overruled or materially distinguished
 *  4. For pre-1996 cases or cases returning 404 — search the commercial
 *     law report databases directly
 *
 * ── Supported neutral citation patterns ──────────────────────────────────────
 *
 *   [YEAR] UKSC NUMBER          → Supreme Court
 *   [YEAR] UKHL NUMBER          → House of Lords
 *   [YEAR] UKPC NUMBER          → Privy Council
 *   [YEAR] EWCA Civ NUMBER      → Court of Appeal (Civil)
 *   [YEAR] EWCA Crim NUMBER     → Court of Appeal (Criminal)
 *   [YEAR] EWHC NUMBER (Div)    → High Court with division
 *   [YEAR] EWHC NUMBER          → High Court (no division — search fallback)
 *   [YEAR] UKUT NUMBER (Chamber)→ Upper Tribunal
 *   [YEAR] UKFTT NUMBER (Tax)   → First-tier Tribunal (Tax)
 *   [YEAR] UKEAT NUMBER         → Employment Appeal Tribunal
 */

import { parseTnaCitation } from "./tna";

const BAILII_BASE = "https://www.bailii.org";

export interface CaseLink {
    /** The original citation string passed in */
    citation: string;
    /** The case name extracted from the citation (everything before the year) */
    caseName: string;
    /** The constructed or search URL */
    url: string;
    /** true = direct link to a specific judgment; false = search results page */
    isDirectLink: boolean;
    /** Human-readable label for the court */
    court: string;
    /** Source repository: "BAILII" or "TNA" */
    source: "BAILII" | "TNA";
}

export type VerificationStatus =
    | "VERIFIED" // HTTP 200 and case name found in page
    | "EXISTS" // HTTP 200 but name match inconclusive
    | "NOT_FOUND" // HTTP 404 — citation likely hallucinated or URL wrong
    | "SEARCH_ONLY" // No direct link constructed — cannot auto-verify
    | "ERROR"; // Network/timeout error during check

export interface VerifiedCaseLink extends CaseLink {
    status: VerificationStatus;
    /** Confidence 0–100 for this individual citation */
    confidence: number;
    /** Human-readable explanation of the verification result */
    verificationNote: string;
}

export interface VerificationSummary {
    links: VerifiedCaseLink[];
    /** Overall citation confidence 0–100 */
    citationConfidence: number;
    /** Number of citations that resolved on BAILII or TNA */
    verified: number;
    /** Number of citations that returned 404 */
    notFound: number;
    /** Number that could not be auto-checked (search-only or error) */
    unverifiable: number;
}

// Map of EWHC division abbreviations used in citations to BAILII path segments
const EWHC_DIVISION_MAP: Record<string, string> = {
    Comm: "Comm",
    Commercial: "Comm",
    QB: "QB",
    "Queen's Bench": "QB",
    "King's Bench": "KB",
    KB: "KB",
    Ch: "Ch",
    Chancery: "Ch",
    Pat: "Pat",
    Patents: "Pat",
    Admin: "Admin",
    Administrative: "Admin",
    TCC: "TCC",
    Technology: "TCC",
    Fam: "Fam",
    Family: "Fam",
    Admiralty: "Admlty",
    Admlty: "Admlty",
    Mercantile: "Mercantile",
    Costs: "Costs",
    IPEC: "IPEC",
    Media: "IPEC",
};

// Map of UKUT chamber abbreviations
const UKUT_CHAMBER_MAP: Record<string, string> = {
    AAC: "AAC",
    IAC: "IAC",
    LC: "LC",
    TCC: "TCC",
    Tax: "TCC",
};

function buildSearchUrl(query: string): string {
    return `${BAILII_BASE}/cgi-bin/find.pl?query=${encodeURIComponent(query)}&method=boolean`;
}

function extractCaseName(citation: string): string {
    // Case name is typically everything before the year bracket, e.g.
    // "Donoghue v Stevenson [1932] AC 562 — ..."
    // Strip holdings (after em dash or long dash)
    const withoutHolding = citation.split(/\s+[—–]\s+/)[0].trim();
    // Remove the citation part (from the first '[' onward)
    const nameOnly = withoutHolding.replace(/\[.*$/, "").trim();
    return nameOnly || withoutHolding;
}

/**
 * Parse a single case citation string and return a CaseLink.
 *
 * @param citation - A citation such as:
 *   "Donoghue v Stevenson [1932] AC 562 — ..."
 *   "Triple Point Technology v PTT [2021] UKSC 29 — ..."
 *   "St Albans v ICL [1996] EWCA Civ 1296 — ..."
 */
export function parseCitation(citation: string): CaseLink {
    const caseName = extractCaseName(citation);
    const searchUrl = buildSearchUrl(caseName || citation.slice(0, 80));

    // Try TNA first for newer cases (2003+)
    const tnaLink = parseTnaCitation(citation);
    if (tnaLink) {
        return {
            ...tnaLink,
            source: "TNA",
        };
    }

    const fallback = (court: string): CaseLink => ({
        citation,
        caseName,
        url: searchUrl,
        isDirectLink: false,
        court,
        source: "BAILII",
    });

    // ── UK Supreme Court ─────────────────────────────────────────────────────
    const uksc = citation.match(/\[(\d{4})\]\s+UKSC\s+(\d+)/i);
    if (uksc) {
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/uk/cases/UKSC/${uksc[1]}/${uksc[2]}.html`,
            isDirectLink: true,
            court: "UK Supreme Court",
            source: "BAILII",
        };
    }

    // ── House of Lords ────────────────────────────────────────────────────────
    const ukhl = citation.match(/\[(\d{4})\]\s+UKHL\s+(\d+)/i);
    if (ukhl) {
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/uk/cases/UKHL/${ukhl[1]}/${ukhl[2]}.html`,
            isDirectLink: true,
            court: "House of Lords",
            source: "BAILII",
        };
    }

    // ── Privy Council ─────────────────────────────────────────────────────────
    const ukpc = citation.match(/\[(\d{4})\]\s+UKPC\s+(\d+)/i);
    if (ukpc) {
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/uk/cases/UKPC/${ukpc[1]}/${ukpc[2]}.html`,
            isDirectLink: true,
            court: "Privy Council",
            source: "BAILII",
        };
    }

    // ── Court of Appeal (Civil) ───────────────────────────────────────────────
    const ewcaCiv = citation.match(/\[(\d{4})\]\s+EWCA\s+Civ\s+(\d+)/i);
    if (ewcaCiv) {
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/ew/cases/EWCA/Civ/${ewcaCiv[1]}/${ewcaCiv[2]}.html`,
            isDirectLink: true,
            court: "Court of Appeal (Civil Division)",
            source: "BAILII",
        };
    }

    // ── Court of Appeal (Criminal) ────────────────────────────────────────────
    const ewcaCrim = citation.match(/\[(\d{4})\]\s+EWCA\s+Crim\s+(\d+)/i);
    if (ewcaCrim) {
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/ew/cases/EWCA/Crim/${ewcaCrim[1]}/${ewcaCrim[2]}.html`,
            isDirectLink: true,
            court: "Court of Appeal (Criminal Division)",
            source: "BAILII",
        };
    }

    // ── High Court with division, e.g. [2022] EWHC 440 (Comm) ───────────────
    const ewhcWithDiv = citation.match(
        /\[(\d{4})\]\s+EWHC\s+(\d+)\s+\(([^)]+)\)/i,
    );
    if (ewhcWithDiv) {
        const rawDiv = ewhcWithDiv[3].trim();
        const divPath = EWHC_DIVISION_MAP[rawDiv] ?? rawDiv;
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/ew/cases/EWHC/${divPath}/${ewhcWithDiv[1]}/${ewhcWithDiv[2]}.html`,
            isDirectLink: true,
            court: `High Court (${rawDiv})`,
            source: "BAILII",
        };
    }

    // ── High Court without division — cannot determine path, fall back ────────
    const ewhcNoDiv = citation.match(/\[(\d{4})\]\s+EWHC\s+(\d+)/i);
    if (ewhcNoDiv) {
        // Try the search with the case name + year for best results
        return {
            citation,
            caseName,
            url: buildSearchUrl(`${caseName} ${ewhcNoDiv[1]}`),
            isDirectLink: false,
            court: "High Court",
            source: "BAILII",
        };
    }

    // ── Employment Appeal Tribunal ────────────────────────────────────────────
    const ukeat = citation.match(/\[(\d{4})\]\s+UKEAT\s+[\/\d]+/i);
    if (ukeat) {
        return fallback("Employment Appeal Tribunal");
    }

    // ── Upper Tribunal ────────────────────────────────────────────────────────
    const ukut = citation.match(/\[(\d{4})\]\s+UKUT\s+(\d+)\s*\(([^)]+)\)/i);
    if (ukut) {
        const chamber = UKUT_CHAMBER_MAP[ukut[3].trim()] ?? ukut[3].trim();
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/uk/cases/UKUT/${chamber}/${ukut[1]}/${ukut[2]}.html`,
            isDirectLink: true,
            court: `Upper Tribunal (${ukut[3]})`,
            source: "BAILII",
        };
    }

    // ── First-tier Tribunal (Tax) ─────────────────────────────────────────────
    const ukftt = citation.match(/\[(\d{4})\]\s+UKFTT\s+(\d+)\s*\(TC\)/i);
    if (ukftt) {
        return {
            citation,
            caseName,
            url: `${BAILII_BASE}/uk/cases/UKFTT/TC/${ukftt[1]}/${ukftt[2]}.html`,
            isDirectLink: true,
            court: "First-tier Tribunal (Tax)",
            source: "BAILII",
        };
    }

    // ── Old-style law report citations (AC, QB, WLR, All ER, etc.) ───────────
    // e.g. "[1932] AC 562", "[1976] QB 142" — no direct BAILII path available;
    // return a search so the user can still find the case.
    const oldStyle = citation.match(
        /\[(\d{4})\]\s+(?:AC|QB|KB|WLR|All\s+ER|Ch|Fam|IRLR|ICR|BCLC|Lloyd|BCC)\s+\d+/i,
    );
    if (oldStyle) {
        return fallback("(pre-neutral citation — search BAILII)");
    }

    // ── Total fallback ────────────────────────────────────────────────────────
    return fallback("(unrecognised citation format — search BAILII)");
}

/**
 * Parse an array of citation strings and return CaseLinks for each.
 * Safe to call with an empty array.
 */
export function parseCitations(citations: string[]): CaseLink[] {
    return citations.map(parseCitation);
}

/**
 * Attempt to verify a single direct link by fetching the page and
 * checking the case name appears in the HTML response.
 *
 * Uses a short timeout (8 s) so slow responses don't stall the
 * closing report. On timeout or network error returns status "ERROR".
 */
async function verifyDirectCaseLink(link: CaseLink): Promise<VerifiedCaseLink> {
    if (!link.isDirectLink) {
        return {
            ...link,
            status: "SEARCH_ONLY",
            confidence: 65,
            verificationNote:
                `Pre-neutral citation or specialist tribunal — no direct ${link.source} URL can be constructed. ` +
                "These are typically genuine older cases (pre-2001) cited from established legal knowledge. " +
                "Use the search link to locate the case and verify the holding.",
        };
    }

    try {
        const res = await fetch(link.url, {
            method: "GET",
            headers: { Accept: "text/html" },
            signal: AbortSignal.timeout(8_000),
        });

        if (res.status === 404) {
            return {
                ...link,
                status: "NOT_FOUND",
                confidence: 10,
                verificationNote:
                    `${link.source} returned 404 for the constructed URL. This citation may be hallucinated, ` +
                    `incorrectly formatted, or the case number may be wrong. ` +
                    `Do not rely on this citation without independent verification via a legal database.`,
            };
        }

        if (!res.ok) {
            return {
                ...link,
                status: "ERROR",
                confidence: 55,
                verificationNote: `${link.source} returned HTTP ${res.status}. Could not confirm automatically — verify manually via the link provided.`,
            };
        }

        // Page exists — check if the case name appears in the HTML
        const html = await res.text();
        const normalise = (s: string) =>
            s.toLowerCase().replace(/[^a-z0-9]/g, "");

        // Split case name into significant tokens (ignore "v", "ltd", "plc" etc.)
        const stopWords = new Set([
            "v",
            "vs",
            "and",
            "the",
            "in",
            "re",
            "ex",
            "parte",
            "ltd",
            "plc",
            "llp",
            "lp",
            "inc",
            "co",
            "corp",
        ]);
        const tokens = link.caseName
            .toLowerCase()
            .split(/\s+/)
            .filter((t) => t.length > 2 && !stopWords.has(t))
            .map((t) => t.replace(/[^a-z0-9]/g, ""));

        const htmlNorm = normalise(html);
        const matchedTokens = tokens.filter((t) => htmlNorm.includes(t));
        const matchRatio =
            tokens.length > 0 ? matchedTokens.length / tokens.length : 0;

        if (matchRatio >= 0.5) {
            return {
                ...link,
                status: "VERIFIED",
                confidence: 92,
                verificationNote:
                    `Confirmed on ${link.source} — page exists and case name matched in judgment text. ` +
                    `Two residual checks remain for legal professionals: ` +
                    `(1) read the judgment to confirm the AI's holding summary is accurate; ` +
                    `(2) run a citator check (Westlaw Cases+ or LexisNexis Case Analysis) to confirm ` +
                    `the case has not been overruled or materially distinguished since.`,
            };
        } else {
            return {
                ...link,
                status: "EXISTS",
                confidence: 75,
                verificationNote:
                    `${link.source} page exists at this URL but automatic name matching was inconclusive. ` +
                    `Click the link to confirm the parties match, then verify the holding and ` +
                    `check subsequent treatment via a citator service.`,
            };
        }
    } catch (err) {
        const isTimeout = err instanceof Error && err.name === "TimeoutError";
        return {
            ...link,
            status: "ERROR",
            confidence: 55,
            verificationNote: isTimeout
                ? `${link.source} did not respond within 8 seconds — the case likely exists but could not be confirmed automatically. Verify via the link.`
                : `Network error during verification: ${err instanceof Error ? err.message : String(err)}. Verify via the link.`,
        };
    }
}

/**
 * Verify all citations in parallel (max 6 concurrent requests to be polite)
 * and return a VerificationSummary with per-citation results and
 * an overall citation confidence score.
 */
export async function verifyCitations(
    citations: string[],
): Promise<VerificationSummary> {
    const links = parseCitations(citations);

    // Process in batches of 6
    const BATCH = 6;
    const verified: VerifiedCaseLink[] = [];
    for (let i = 0; i < links.length; i += BATCH) {
        const batch = links.slice(i, i + BATCH);
        const results = await Promise.all(batch.map(verifyDirectCaseLink));
        verified.push(...results);
    }

    const verifiedCount = verified.filter(
        (v) => v.status === "VERIFIED" || v.status === "EXISTS",
    ).length;
    const notFoundCount = verified.filter(
        (v) => v.status === "NOT_FOUND",
    ).length;
    const unverifiableCount = verified.filter(
        (v) => v.status === "SEARCH_ONLY" || v.status === "ERROR",
    ).length;
    // Citation confidence: average per-citation scores, weighted so that
    // NOT_FOUND citations drag the score down significantly.
    // A score of 90+ means all or nearly all citations verified on BAILII or TNA.
    let citationConfidence = 100;
    if (verified.length > 0) {
        const totalWeight = verified.reduce((sum, v) => sum + v.confidence, 0);
        citationConfidence = Math.round(totalWeight / verified.length);
    }

    return {
        links: verified,
        citationConfidence,
        verified: verifiedCount,
        notFound: notFoundCount,
        unverifiable: unverifiableCount,
    };
}

/**
 * Build a plain-language confidence summary for inclusion in the closing report.
 *
 * Covers four dimensions:
 *  1. Legislation (statute table coverage)
 *  2. Case citations (BAILII/TNA live verification)
 *  3. Risk assessment (adversarial agent score)
 *  4. Overall recommendation
 */
export function buildConfidenceSummary(
    verificationSummary: VerificationSummary,
    enforceabilityScore: number | undefined,
    totalStatutes: number,
    knownStatutes: number,
): string {
    const { citationConfidence, verified, notFound, unverifiable, links } =
        verificationSummary;

    const legislationPct =
        totalStatutes > 0
            ? Math.round((knownStatutes / totalStatutes) * 100)
            : 0;

    const riskScore = enforceabilityScore ?? 0;

    // Weight: legislation 25%, citations 35%, risk assessment 40%
    const overall = Math.round(
        legislationPct * 0.25 + citationConfidence * 0.35 + riskScore * 0.4,
    );

    const overallLabel =
        overall >= 88
            ? "High — verified statutory framework, confirmed case law, adversarially reviewed draft"
            : overall >= 75
              ? "Good — strong verification with minor gaps; review by a qualified solicitor before execution"
              : overall >= 60
                ? "Moderate — some citations or statutes unverified; careful legal review recommended"
                : overall >= 40
                  ? "Low — material verification gaps; do not execute without full solicitor review"
                  : "Very Low — significant issues detected; independent legal review essential";

    const lines: string[] = [
        `## Output Confidence Assessment`,
        ``,
        `> This section is an automated estimate of the reliability of this AI-generated output. `,
        `> It does **not** substitute for qualified legal review.`,
        ``,
        `| Dimension | Score | Detail |`,
        `|---|---|---|`,
        `| Legislation coverage | ${legislationPct}% | ${knownStatutes} of ${totalStatutes} statutes verified against legislation.gov.uk |`,
        `| Case citation verification | ${citationConfidence}% | ${verified} confirmed on BAILII/TNA · ${notFound} not found · ${unverifiable} pre-neutral / unverifiable |`,
        `| Enforceability (AI risk review) | ${riskScore}/100 | Adversarial peer review — higher = fewer material weaknesses |`,
        `| **Overall output confidence** | **${overall}%** | **${overallLabel}** |`,
        ``,
    ];

    if (notFound > 0) {
        const notFoundNames = links
            .filter((l) => l.status === "NOT_FOUND")
            .map((l) => `- **${l.caseName}** (${l.source}) — ${l.url}`)
            .join("\n");
        lines.push(
            `### ⚠️ Citations Not Found (${notFound})`,
            ``,
            `The following citations returned HTTP 404 from their expected repository and may be hallucinated or incorrectly formatted. ` +
                `Do not rely on them without independent verification:`,
            ``,
            notFoundNames,
            ``,
        );
    }

    if (unverifiable > 0) {
        lines.push(
            `### Citations Not Auto-Verifiable (${unverifiable})`,
            ``,
            `These citations use older report formats or specialist tribunals where a direct URL ` +
                `cannot be constructed. Use the search links provided to locate them manually.`,
            ``,
        );
    }

    lines.push(
        `### What This Score Means`,
        ``,
        `- **Legislation confidence** reflects whether the cited statutes are in our verified ` +
            `legislation.gov.uk lookup table — a curated list of confirmed UK Acts and Statutory Instruments ` +
            `with direct URLs. A score of 90%+ means the statutory framework is solidly grounded in ` +
            `real, confirmed legislation.`,
        ``,
        `- **Citation confidence** reflects live verification against **BAILII** (for historical cases) ` +
            `and **The National Archives (TNA)** (the UK government's official repository for judgments since 2003). ` +
            `A ✅ VERIFIED citation means the page was found and the case name matched the judgment text. ` +
            `**What this score does not cover:** (1) Whether the AI's summary precisely reflects the judgment; ` +
            `(2) Whether the case has been overruled since — always run a citator check (Westlaw/LexisNexis).`,
        ``,
        `- **Enforceability score** reflects the risk agent's adversarial review of the draft contract. ` +
            `A score of 80+ indicates a well-formed draft with only minor issues under English law.`,
        ``,
        `- **Overall confidence** is a weighted composite (legislation 25%, citations 35%, ` +
            `enforceability 40%). A score of 88%+ reflects a high-quality, well-verified draft.`,
        ``,
        `- **This report is not legal advice.** MyCounsel is a drafting assistance tool, not a law firm. ` +
            `Output should be reviewed by a qualified solicitor before execution.`,
        ``,
    );

    return lines.join("\n");
}

/**
 * Format a VerifiedCaseLink as a Markdown string with status badge and link.
 */
export function formatVerifiedCitationMarkdown(
    link: VerifiedCaseLink,
    holdingSummary?: string,
): string {
    const statusBadge =
        link.status === "VERIFIED"
            ? `✅ Verified on ${link.source}`
            : link.status === "EXISTS"
              ? `🟡 Page exists on ${link.source} (name match inconclusive)`
              : link.status === "NOT_FOUND"
                ? `🔴 NOT FOUND on ${link.source} — verify independently`
                : link.status === "SEARCH_ONLY"
                  ? `🔍 Search ${link.source} (no direct link)`
                  : `⚠️ Verification error on ${link.source} — check manually`;

    const linkLabel = link.isDirectLink
        ? `Open on ${link.source} →`
        : `Search ${link.source} →`;
    const courtNote = link.court ? ` *(${link.court})*` : "";
    const lines: string[] = [
        `**${link.caseName}**${courtNote} — ${statusBadge}`,
    ];
    if (holdingSummary) {
        lines.push(`> *${holdingSummary}*`);
        lines.push(`> *(AI interpretation — verify against judgment)*`);
    }
    lines.push(`[${linkLabel}](${link.url})`);
    if (link.status === "NOT_FOUND" || link.status === "ERROR") {
        lines.push(`> ⚠️ ${link.verificationNote}`);
    }
    return lines.join("  \n");
}
