/**
 * Formats the Risk Agent's JSON output as a Markdown Legal Standing Report
 */

import { ContractState } from './state';

export function formatRiskReport(state: ContractState): string {
  const report = state.risk_report;
  const latestDraft = state.draft_versions[state.draft_versions.length - 1];

  if (!report) {
    return '# Legal Standing Report\n\n_Risk assessment not yet complete._';
  }

  const scoreEmoji =
    report.enforceability_score >= 75
      ? '🟢'
      : report.enforceability_score >= 50
        ? '🟡'
        : '🔴';

  const scoreLabel =
    report.enforceability_score >= 90
      ? 'Exceptional'
      : report.enforceability_score >= 75
        ? 'Good'
        : report.enforceability_score >= 60
          ? 'Adequate — Notable Gaps'
          : report.enforceability_score >= 40
            ? 'Significant Weaknesses'
            : 'Do Not Execute — Fundamental Defects';

  const lines: string[] = [
    `# Legal Standing Report`,
    ``,
    `**Reference:** MyCounsel Contract \`${state.id}\`  `,
    `**Agreement:** ${state.inputs.intent}  `,
    `**Parties:** ${state.inputs.parties.map((p) => `${p.name} (${p.role})`).join(' · ')}  `,
    `**Draft Version:** ${latestDraft?.version ?? 'N/A'}  `,
    `**Governing Law:** England & Wales  `,
    `**Report generated by:** Agent D — Claude 3.5 Sonnet (Adversarial Peer Review)`,
    ``,
    `---`,
    ``,
    `## Enforceability Score`,
    ``,
    `### ${scoreEmoji} ${report.enforceability_score} / 100 — ${scoreLabel}`,
    ``,
    `**Primary Governing Statute:** ${report.statutory_basis}`,
    report.anchor_case ? `**Anchor Case:** ${report.anchor_case}` : '',
    ``,
    `---`,
    ``,
    `## Identified Legal Vulnerabilities`,
    ``,
  ];

  report.warnings.forEach((warning, idx) => {
    lines.push(`### ${idx + 1}. ${warning.title}`);
    lines.push('');
    lines.push(warning.detail);
    lines.push('');
    lines.push(`> **Statutory Basis:** ${warning.statutory_basis}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  });

  lines.push(`## Recommendation`);
  lines.push('');
  lines.push(report.recommendation);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(
    `_This report was generated by an AI legal assistant and does not constitute legal advice. Please consult a qualified solicitor before executing this agreement._`
  );

  return lines.filter((l) => l !== null).join('\n');
}
