/**
 * Formats the Risk Agent's JSON output as a Markdown Legal Standing Report
 * and a full Closing Report on approval.
 */

import { ContractState } from "./state";
import {
    verifyCitations,
    buildConfidenceSummary,
    formatVerifiedCitationMarkdown,
    VerificationSummary,
} from "./integrations/bailii";

// Statutes we can confirm exist via the legislation.gov.uk lookup table
import { STATUTE_LOOKUP_KEYS } from "./integrations/legislation";

export function formatRiskReport(state: ContractState): string {
    const report = state.risk_report;
    const latestDraft = state.draft_versions[state.draft_versions.length - 1];

    if (!report) {
        return "# Legal Standing Report\n\n_Risk assessment not yet complete._";
    }

    const scoreEmoji =
        report.enforceability_score >= 75
            ? "🟢"
            : report.enforceability_score >= 50
              ? "🟡"
              : "🔴";

    const scoreLabel =
        report.enforceability_score >= 90
            ? "Exceptional"
            : report.enforceability_score >= 75
              ? "Good"
              : report.enforceability_score >= 60
                ? "Adequate — Notable Gaps"
                : report.enforceability_score >= 40
                  ? "Significant Weaknesses"
                  : "Do Not Execute — Fundamental Defects";

    const lines: string[] = [
        `# Legal Standing Report`,
        ``,
        `**Reference:** MyCounsel Contract \`${state.id}\`  `,
        `**Agreement:** ${state.inputs.intent}  `,
        `**Parties:** ${state.inputs.parties.map((p) => `${p.name} (${p.role})`).join(" · ")}  `,
        `**Draft Version:** ${latestDraft?.version ?? "N/A"}  `,
        `**Governing Law:** England & Wales  `,
        `**Report generated by:** Agent D — Claude 3.5 Sonnet (Adversarial Peer Review)`,
        ``,
        `---`,
        ``,
        `## Enforceability Score`,
        ``,
        `### ${scoreEmoji} ${report.enforceability_score} / 100 — ${scoreLabel}`,
        ``,
        `**Primary Governing Statute:** ${report.statutory_basis}`,
        report.anchor_case ? `**Anchor Case:** ${report.anchor_case}` : "",
        ``,
        `---`,
        ``,
        `## Identified Legal Vulnerabilities`,
        ``,
    ];

    report.warnings.forEach((warning, idx) => {
        lines.push(`### ${idx + 1}. ${warning.title}`);
        lines.push("");
        lines.push(warning.detail);
        lines.push("");
        lines.push(`> **Statutory Basis:** ${warning.statutory_basis}`);
        lines.push("");
        lines.push("---");
        lines.push("");
    });

    lines.push(`## Recommendation`);
    lines.push("");
    lines.push(report.recommendation);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push(
        `_This report was generated by an AI legal assistant and does not constitute legal advice. Please consult a qualified solicitor before executing this agreement._`,
    );

    return lines.filter((l) => l !== null).join("\n");
}

// ─── Closing Report ───────────────────────────────────────────────────────────

/**
 * Generates a comprehensive closing report on approval covering:
 * - Agreement summary
 * - Statutory framework applied (with legislation.gov.uk links)
 * - Case law and precedents cited
 * - Full risk assessment with impact ratings
 * - Resolved vs deferred issues
 * - Revision history
 */
export async function formatClosingReport(
    state: ContractState,
): Promise<string> {
    const report = state.risk_report;
    const now = new Date().toLocaleDateString("en-GB", {
        day: "numeric",
        month: "long",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });

    const scoreLabel = !report
        ? "N/A"
        : report.enforceability_score >= 90
          ? "Exceptional"
          : report.enforceability_score >= 75
            ? "Good"
            : report.enforceability_score >= 60
              ? "Adequate — Notable Gaps"
              : report.enforceability_score >= 40
                ? "Significant Weaknesses"
                : "Do Not Execute";

    const contractTypeLabel = state.contract_type
        ? state.contract_type.replace(/_/g, " ")
        : "Commercial Agreement";

    const partiesLine = state.inputs.parties
        .map(
            (p) =>
                `${p.name} (${p.role})${p.co_number ? ` — Companies House No. ${p.co_number}` : ""}`,
        )
        .join("\n- ");

    const lines: string[] = [
        `# MyCounsel Closing Legal Report`,
        ``,
        `| | |`,
        `|---|---|`,
        `| **Reference** | ${state.ref} |`,
        `| **Agreement** | ${state.name} |`,
        `| **Type** | ${contractTypeLabel} |`,
        `| **Governing Law** | England & Wales |`,
        `| **Draft Versions** | ${state.draft_versions.length} |`,
        `| **Mode** | ${state.mode === "REVIEW" ? "Contract Review & Improvement" : "New Draft"} |`,
        `| **Final Score** | ${report ? `${report.enforceability_score}/100 — ${scoreLabel}` : "N/A"} |`,
        `| **Report Generated** | ${now} |`,
        ``,
        `**Parties:**`,
        `- ${partiesLine}`,
        ``,
        `---`,
        ``,
        `## 1. Statutory Framework Applied`,
        ``,
        `The following UK legislation was researched and applied in the drafting of this agreement:`,
        ``,
    ];

    if (state.legal_context.statutes.length > 0) {
        state.legal_context.statutes.forEach((s) => {
            lines.push(`- ${s}`);
        });
    } else {
        lines.push("_No statutes recorded._");
    }

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## 2. Case Law & Precedents");
    lines.push("");

    // ── Live BAILII verification ──────────────────────────────────────────────
    let verificationSummary: VerificationSummary | null = null;
    if (state.legal_context.precedents.length > 0) {
        verificationSummary = await verifyCitations(
            state.legal_context.precedents,
        );

        lines.push(
            "> ⚠️ **AI-generated citations — live verification performed.** " +
                "Each citation below has been checked against **BAILII** (historical) and **The National Archives (TNA)** (modern). " +
                "A ✅ badge means the page was found and the case name matched. " +
                "A 🔴 badge means the URL returned 404 — that citation may be hallucinated. " +
                "Even verified citations: the **holding summary is an AI interpretation** and must be " +
                "checked against the actual judgment before reliance.",
        );
        lines.push("");
        lines.push(
            "The following UK cases were cited in the legal research for this agreement:",
        );
        lines.push("");

        verificationSummary.links.forEach((link, i) => {
            const holdingMatch = link.citation.match(/[—–]\s*(.+)$/);
            const holding = holdingMatch ? holdingMatch[1].trim() : undefined;
            lines.push(`### ${i + 1}. ${link.caseName}`);
            lines.push("");
            lines.push(formatVerifiedCitationMarkdown(link, holding));
            lines.push("");
        });
    } else {
        lines.push("_No case law recorded._");
    }

    if (state.legal_context.anchor_case_summary) {
        lines.push("");
        lines.push("**Anchor Case Summary:**");
        lines.push("");
        lines.push(`> ${state.legal_context.anchor_case_summary}`);
        lines.push("");
        lines.push(
            "_Note: The anchor case summary above is an AI interpretation. " +
                "Verify the case and its ratio decidendi independently via the links above._",
        );
    }

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## 3. Risk Assessment");
    lines.push("");

    if (report) {
        const scoreEmoji =
            report.enforceability_score >= 75
                ? "🟢"
                : report.enforceability_score >= 50
                  ? "🟡"
                  : "🔴";

        lines.push(
            `### ${scoreEmoji} Final Enforceability Score: ${report.enforceability_score}/100 — ${scoreLabel}`,
        );
        lines.push("");
        lines.push(`**Primary Governing Statute:** ${report.statutory_basis}`);
        if (report.anchor_case) {
            lines.push(`**Anchor Case:** ${report.anchor_case}`);
        }
        lines.push("");

        // Issues found — with impact ratings
        if (report.warnings.length > 0) {
            lines.push("### Issues Identified");
            lines.push("");
            lines.push("| # | Impact | Issue | Statutory Basis |");
            lines.push("|---|---|---|---|");

            const IMPACT_ORDER: Record<string, number> = {
                HIGH: 0,
                MEDIUM: 1,
                LOW: 2,
            };
            const sorted = [...report.warnings].sort(
                (a, b) =>
                    (IMPACT_ORDER[a.impact] ?? 1) -
                    (IMPACT_ORDER[b.impact] ?? 1),
            );

            sorted.forEach((w, i) => {
                const impactLabel =
                    w.impact === "HIGH"
                        ? "🔴 HIGH"
                        : w.impact === "LOW"
                          ? "⚪ LOW"
                          : "🟡 MEDIUM";
                lines.push(
                    `| ${i + 1} | ${impactLabel} | **${w.title}** — ${w.detail} | ${w.statutory_basis} |`,
                );
            });

            lines.push("");
        }

        // Resolved issues (tracked by risk agent across revision cycles)
        const resolvedIssues = (report as any).resolved_issues as
            | string[]
            | undefined;
        if (resolvedIssues && resolvedIssues.length > 0) {
            lines.push("### ✅ Issues Resolved During Revision");
            lines.push("");
            resolvedIssues.forEach((r) => {
                lines.push(`- ${r}`);
            });
            lines.push("");
        }

        // Remaining issues (current warnings = accepted risks or to be addressed)
        if (report.warnings.length > 0) {
            lines.push("### Remaining Issues (Accepted Risk)");
            lines.push("");
            lines.push(
                "The following issues were identified at approval. The approving party accepts the risk associated with these points:",
            );
            lines.push("");
            report.warnings.forEach((w, i) => {
                const impactLabel =
                    w.impact === "HIGH"
                        ? "🔴 HIGH"
                        : w.impact === "LOW"
                          ? "⚪ LOW"
                          : "🟡 MEDIUM";
                lines.push(`${i + 1}. **[${impactLabel}] ${w.title}**`);
                lines.push(`   ${w.detail}`);
                lines.push(`   *${w.statutory_basis}*`);
                lines.push("");
            });
        }

        lines.push("**Recommendation:**");
        lines.push("");
        lines.push(report.recommendation);
    } else {
        lines.push("_Risk assessment not completed._");
    }

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## 4. Revision History");
    lines.push("");

    if (state.draft_versions.length === 1) {
        lines.push(
            "This agreement was approved on the initial draft without revision.",
        );
    } else {
        lines.push(
            `This agreement went through **${state.draft_versions.length} draft versions** before approval.`,
        );
        lines.push("");
        lines.push("| Version | Date | Author |");
        lines.push("|---|---|---|");
        state.draft_versions.forEach((v) => {
            const date = new Date(v.created_at).toLocaleDateString("en-GB", {
                day: "numeric",
                month: "short",
                year: "numeric",
                hour: "2-digit",
                minute: "2-digit",
            });
            lines.push(`| v${v.version} | ${date} | ${v.author} |`);
        });

        if (state.lawyer_notes) {
            lines.push("");
            lines.push("**Final Revision Notes:**");
            lines.push("");
            lines.push(`> ${state.lawyer_notes}`);
        }
    }

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## 5. Execution");
    lines.push("");
    lines.push(
        `This agreement has been approved by the instructing party and ${
            state.signature_request_id &&
            !state.signature_request_id.startsWith("demo-")
                ? `dispatched for electronic signature via Adobe Sign (Request ID: \`${state.signature_request_id}\`).`
                : "is ready for execution by all parties."
        }`,
    );
    // ── Confidence assessment ─────────────────────────────────────────────────
    lines.push("");
    lines.push("---");
    lines.push("");

    // Count how many statutes are in our verified lookup table
    const knownStatuteKeys = STATUTE_LOOKUP_KEYS;
    const knownCount = state.legal_context.statutes.filter((s) =>
        knownStatuteKeys.some((k) =>
            s.toLowerCase().includes(
                k
                    .replace(/\s*\(\d+\)$/, "")
                    .toLowerCase()
                    .slice(0, 20),
            ),
        ),
    ).length;

    if (verificationSummary) {
        lines.push(
            buildConfidenceSummary(
                verificationSummary,
                state.risk_report?.enforceability_score,
                state.legal_context.statutes.length,
                knownCount,
            ),
        );
        lines.push("");
        lines.push("---");
        lines.push("");
    }

    lines.push("## Important Notices");
    lines.push("");
    lines.push(
        "**Case Citation Verification:** Citations were generated by an AI model and have been " +
            "automatically checked against BAILII (historical) and The National Archives (modern). " +
            "A ✅ status means the page was found and the case name matched. " +
            "A 🔴 NOT FOUND status means the citation may be hallucinated — do not rely on it. " +
            "Even verified citations: always read the actual judgment before relying on the stated holding.",
    );
    lines.push("");
    lines.push(
        "**No Legal Advice:** This closing report was generated automatically by MyCounsel. " +
            "It is provided for record-keeping and reference purposes only and does not constitute legal advice. " +
            "The AI-generated risk assessment, statutory analysis, and case citations should be reviewed and " +
            "verified by a qualified solicitor before reliance.",
    );
    lines.push("");
    lines.push(`*MyCounsel · Ref: ${state.ref} · ${now}*`);

    return lines.join("\n");
}
